# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo_pub_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
