# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171202_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
