# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_photo_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.FileField(upload_to='photos'),
        ),
    ]
